language: scala
scala:
   - 2.11.11
   - 2.11.12
   # - 2.12.0 doesn't work due to SI-7046
   - 2.12.1
   - 2.12.2
   - 2.12.3
   - 2.12.4
jdk:
  - openjdk8

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.coursier/cache/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean "scalafmt --test" coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
